# This is a basic workflow to help you get started with Actions
name: CD

on:
  # Triggers the workflow on  pull request events but only for the "main" branch
  push:
    branches: [ "main" ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    
    strategy:
        matrix:
            node-version: [ 15.x ]
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: use node.js ${{matrix.node-version}}
        uses: actions/setup-node@v3
        with:
            node-version: ${{matrix.node-version}}

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region:  us-east-2

      # Runs a single command using the runners shell
      - name: Install dependencies
        run: npm install

      - name: dev build
        run: npm run build

      - name: pushing code to s3
        run: aws s3 sync build/ s3://devops-sample-task-challange-prod

      - name: Cloudfront Invalidate
        uses: awact/cloudfront-action@master
        env:
            SOURCE_PATH: "/*"
            AWS_REGION:  "us-east-2"
            AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
            AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            DISTRIBUTION_ID: "EPIL57OX09RZD"

